name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for taking the time to come and create an issue. This repo is probably not the place though..."
        pr-message: "Cool, cool... Thank you for improving this repo. However, keep in mind that this is a temporary repo."
